cc_binary(
  name = "adapter",
  srcs = ["adapter/adapter.cc"],
)

cc_binary(
  name = "decorator_functional",
  srcs = ["decorator/functional_decorator.cc"],
)

cc_binary(
  name = "decorator_static",
  srcs = ["decorator/static_decorator.cc"],
)

cc_binary(
  name = "proxy_property",
  srcs = ["proxy/property_proxy.cc"],
)
